version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    healthcheck:
      test: ["CMD", "wget", "-q", "--method=HEAD", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3